#!/usr/bin/env -S deno run --allow-read --allow-run --allow-env
// tf-resource-coverage — does every mutating client method have an actual
// Terraform resource/data-source calling it, not just client-layer plumbing?
//
// pkg/client having a method only proves the CLI can reach an endpoint — the
// client can carry a method for years with zero Terraform surface on top of it
// (registry retention, org secrets, FKE). This reads every func on *Client that
// wraps a newRequest() call out of the github.com/fogpipe/cloud-cli module, and
// cross-references it against every `.client.Method(` call in this repo's
// internal/provider/*.go.
//
// The client is resolved at its LATEST RELEASE, not at the version go.mod pins
// here. Judging the provider against its own pin makes the gate self-satisfying:
// it would stay green while the pin sits two releases behind and every field
// added since is unreachable from HCL. A red build here after a cloud-cli
// release is the signal to bump — see the workspace's provider-sync notes.
//
// New gaps are failures; existing ones are accepted via a checked-in
// baseline (scripts/tf-resource-coverage-baseline.txt) so this doesn't try to
// retroactively judge every pre-existing intentional CLI-only endpoint
// (auth, imperative actions like rollback/deploy, data-plane object ops).
// Shrink the baseline as real coverage gets built; grow it (with
// --update-baseline) only for a deliberate, reviewed new exclusion.
//
// Usage:
//   deno run --allow-read --allow-run --allow-env scripts/tf-resource-coverage.ts
//   deno run --allow-write --allow-read --allow-run --allow-env scripts/tf-resource-coverage.ts --update-baseline

const root = new URL("../", import.meta.url).pathname;
const baselinePath = root + "scripts/tf-resource-coverage-baseline.txt";

// `go list -m` answers with an empty Dir — not an error — when the module is
// known but not yet downloaded, which is the normal state of a fresh CI
// checkout. GOWORK=off so a session tree resolves the released client rather
// than the sibling cloud-cli checkout: this repo builds alone everywhere else.
function moduleDir(mod: string): string {
  const go = (...args: string[]) => {
    const out = new Deno.Command("go", {
      args,
      cwd: root,
      env: { ...Deno.env.toObject(), GOWORK: "off" },
    }).outputSync();
    if (!out.success) {
      throw new Error(`go ${args.join(" ")} failed: ${new TextDecoder().decode(out.stderr)}`);
    }
    return new TextDecoder().decode(out.stdout).trim();
  };
  let dir = go("list", "-m", "-f", "{{.Dir}}", mod);
  if (dir === "") {
    go("mod", "download", mod);
    dir = go("list", "-m", "-f", "{{.Dir}}", mod);
  }
  if (dir === "") throw new Error(`${mod} is not in the module cache after go mod download`);
  return dir;
}

// --- client.go: every *Client method that actually wraps an API call ---
function clientMethods(clientGoPath: string): Set<string> {
  const lines = Deno.readTextFileSync(clientGoPath).split("\n");
  const methods = new Set<string>();
  let current: string | null = null;
  let sawRequest = false;
  const flush = () => {
    if (current && sawRequest) methods.add(current);
    current = null;
    sawRequest = false;
  };
  for (const line of lines) {
    const fn = line.match(/^func \(c \*Client\) ([A-Za-z0-9_]+)\(/);
    if (fn) {
      flush();
      current = fn[1];
      continue;
    }
    if (current && /\bnewRequest\(/.test(line)) sawRequest = true;
    if (current && /^}$/.test(line)) flush();
  }
  flush();
  return methods;
}

// --- internal/provider/*.go: every `.client.Method(` call site ---
function calledMethods(providerDir: string): Set<string> {
  const called = new Set<string>();
  for (const entry of Deno.readDirSync(providerDir)) {
    if (!entry.isFile || !entry.name.endsWith(".go")) continue;
    if (entry.name.endsWith("_test.go")) continue;
    const src = Deno.readTextFileSync(`${providerDir}/${entry.name}`);
    for (const m of src.matchAll(/\.client\.([A-Za-z0-9_]+)\(/g)) {
      called.add(m[1]);
    }
  }
  return called;
}

const available = clientMethods(
  `${moduleDir("github.com/fogpipe/cloud-cli@latest")}/pkg/client/client.go`,
);
const called = calledMethods(`${root}internal/provider`);

const uncovered = [...available].filter((m) => !called.has(m)).sort();

const baseline = new Set(
  (() => {
    try {
      return Deno.readTextFileSync(baselinePath).split("\n").map((l) =>
        l.trim()
      ).filter((l) => l && !l.startsWith("#"));
    } catch {
      return [];
    }
  })(),
);

if (Deno.args.includes("--update-baseline")) {
  const body = uncovered.map((m) => m).join("\n") + "\n";
  Deno.writeTextFileSync(
    baselinePath,
    "# client methods with no Terraform resource/data-source calling them (yet).\n" +
      "# generated by scripts/tf-resource-coverage.ts --update-baseline — only add to\n" +
      "# this deliberately, on review; shrink it as real TF coverage gets built.\n" +
      body,
  );
  console.log(`wrote ${uncovered.length} entries to ${baselinePath}`);
  Deno.exit(0);
}

const newGaps = uncovered.filter((m) => !baseline.has(m));
const stale = [...baseline].filter((m) => !uncovered.includes(m)).sort();

console.log(
  `${available.size} client methods, ${uncovered.length} uncovered by any TF resource, ${baseline.size} in baseline.\n`,
);

if (newGaps.length) {
  console.log("NEW gaps — a client method with no Terraform resource surface:");
  for (const m of newGaps) console.log(`  ✗ ${m}`);
  console.log(
    "\nEither wire it into a resource/data-source, or if it's intentionally " +
      "CLI/API-only, run with --update-baseline and review the diff.",
  );
} else {
  console.log("no new gaps ✓");
}

if (stale.length) {
  console.log(
    `\n${stale.length} baseline entries are now covered — remove from the baseline:`,
  );
  for (const m of stale) console.log(`  · ${m}`);
}

Deno.exit(newGaps.length ? 1 : 0);
